### ISSUE TITLE
MLDS Notes Tracker

### ISSUE THREAD

**Issue by dog-broad** [dog-broad/3_2-Needs#3]
# Unit 1

- [x] What are vectors in machine learning? Explain with examples the different operations performed on them.
- [x] Explain Simpson’s paradox.
- [x] Discuss about Center Limit Theorem and Central Tendencies
- [x] Discuss about statistical hypothesis testing.
- [x] What is P-hacking? Explain with an example
- [x] Discuss Bayesian Inference.
- [x] Explain about matrices and the operations performed on matrices.
- [x] Explain about correlation and causation.

# Unit 2

- [x] What is train/test split of data and how is it implemented in machine learning?
- [x] Explain in detail about Naïve Bayes algorithm.
- [x] Illustrate K-Nearest Neighbours with an example.
- [x] What do you mean by regularization? Explain the different regularization methods.
- [x] What is meant by random forest algorithm? Explain
- [x] Discuss about Support Vector Machines (SVM).
- [x] Discuss in detail about Classification Errors.

# Unit 3

- [x] Explain find –S algorithm with given example (refer Table 1 in image). Give its application. 
- [x] Give an over view of Deep Learning.
- [x] What is a neural network? Explain in detail about its components and how it works.
- [x] Explain the process of learning by rule induction with an example.
- [x] Explain Web scraping in detail.
- [x] Discuss about Traits of Big data 
- [x] Difference between Analysis VS Reporting
- [x] Explain the essential steps in Data science process in business.
- [x] What are the four components of time series? How do you analyze the time series?

# Unit 4

- [x] Describe the concepts of Visualizing Data: Bar Charts, Line Charts, Scatterplots with an example.
- [x] Describe about dimensionality reduction 
- [x] Discuss in detail about packages like Numpy with example 
- [x] Discuss about Manipulating data 
- [x] Explain in detail about Data Cleaning and Munging techniques.
- [x] How to use rescaling features in python?
- [x] Describe the methods in the NLTK package.
- [x] How to split dataset using scikit-learn 

# Unit 5

- [x] Elaborate in detail about any two Recommender systems.
- [x] Define Sentiment Analysis and discuss the different types of Sentiment Analysis (with example)
- [x] Explain about Collaborative filtering systems with example 
- [x] Discuss the text representation techniques in sentiment analysis 
- [x] Explain about working process of recommender system 
- [x] What are the application of Sentiment Analysis 
- [x] Elaborate in detail about Content and collaborative filtering 
- [x] Why Sentiment Analysis is important? Mention Sentiment Analysis applications and examples

**Comment by dog-broad** [comment]
Completed everything by 8ebe9b659b0d5d7340d088f1687db7a8a40126fe
