### ISSUE TITLE
IOTCC Notes Tracker

### ISSUE THREAD

**Issue by dog-broad** [dog-broad/3_2-Needs#4]
# Unit 1

- [x] Describe about Smart grid and Electric vehicles with diagram.
- [x] Brief about Smart Building Management System with a diagram.
- [x] Explain Telematics and Intelligent Transport Systems in IoT?
- [x] SWOT Analysis on IoT
* ~Draw and Describe Panoramic view of IOT applications.~ (I don't like this question, so I won't add this)

# Unit 2

- [x] Explain RFID pillar of IOT.
- [x] Explain M2M Pillar of IOT.
- [x] Explain WSN pillar of IOT.
- [x] Explain SCADA pillar of IOT.
- [ ] Describe each term in DNA of IoT.

# Unit 3

- [ ] Enumerate the contribution of WSN in IoT
- [ ] Conceptualize the TWO (UDP and TCP)Specific protocols required to establish IoT Environment.
- [x] Explain M2M and WSN protocols.
- [x] Explain RFID and SCADA protocols.
- [x] Discuss Standards for M2M.
- [x] Explain Frameworks for WSN.
- [x] Explain the Standards for SCADA.
- [x] Explain the Extensions for RFID standards.
- [ ] Explain Multitier WoT architecture in IoT.
- [ ] Explain the WoT framework Standards Architecture.

# Unit 4

- [x] Elaborate NIST’s SPI Architecture.
- [ ] Describe The Cloud of Things architectural specifications.
- [x] Illustrate about the Cloud Middleware using a Diagram.
- [ ] Describe in brief Four Deployment Models used in cloud for IoT.

# Unit 5

- [ ] Explain the process to transform Home into Smart Home using IoT.
- [x] Briefly discuss about learning in Smart Cities using IoT.
- [ ] Describe the methodology used for Plant and Farming using Cloud in IoT.
- [ ] Describe the procedure to implement Smart Parking using IoT.
- [ ] Indecision service delivery, Data Delivery Pricing

**Comment by dog-broad** [comment]
- [x] SAQ's

# Mid 1

1. State the term IoT with its applications.
2. Write a short note on SWOT analysis of IOT?
3. Draw and Define Telematics Terminal Architecture. 
4. Mention the three different versions of the vehicle-to-grid concept.
5. Draw and Define IOT paradigm and related networks.
6. Brief about Body Sensor Network with diagram?
7. Illustrate the evolution of Identification with a diagram.
8. Differentiate UPC-A and EAN Bar codes.
9. Draw the Sensor Network Architecture.
10. Define Sensor, Actuators, and Transducers?  
11. Define RFID tag with its types?
12. Explain different types of Sensors with Example?
13. Draw Middleware based SCADA system Architecture.
14. Mention the new standards of Wireless Networks for IOT.
15. Mention issues with IOT standardization.

# Mid 2

1. Differentiate WOT and IOT.
2. Compare IoT Red Ocean versus Blue Ocean.
3. Define Cloud Computing.
4. Describe briefly Data caching in IoT.
5. Explain indecision service delivery in IoT.
6. List the Cloud Providers/Open Source Projects for IoT.
7. Mention Cloud Services in IoT.
8. Define Mobile Cloud Computing.
9. Illustrate different Cloud Deployment models for IoT.
10. Compare IOT vs Cloud Computing.

**Comment by dog-broad** [comment]
> * [x]  SAQ's
> 
> # Mid 1
> 1. State the term IoT with its applications.
> 2. Write a short note on SWOT analysis of IOT?
> 3. Draw and Define Telematics Terminal Architecture.
> 4. Mention the three different versions of the vehicle-to-grid concept.
> 5. Draw and Define IOT paradigm and related networks.
> 6. Brief about Body Sensor Network with diagram?
> 7. Illustrate the evolution of Identification with a diagram.
> 8. Differentiate UPC-A and EAN Bar codes.
> 9. Draw the Sensor Network Architecture.
> 10. Define Sensor, Actuators, and Transducers?
> 11. Define RFID tag with its types?
> 12. Explain different types of Sensors with Example?
> 13. Draw Middleware based SCADA system Architecture.
> 14. Mention the new standards of Wireless Networks for IOT.
> 15. Mention issues with IOT standardization.
> 
> # Mid 2
> 1. Differentiate WOT and IOT.
> 2. Compare IoT Red Ocean versus Blue Ocean.
> 3. Define Cloud Computing.
> 4. Describe briefly Data caching in IoT.
> 5. Explain indecision service delivery in IoT.
> 6. List the Cloud Providers/Open Source Projects for IoT.
> 7. Mention Cloud Services in IoT.
> 8. Define Mobile Cloud Computing.
> 9. Illustrate different Cloud Deployment models for IoT.
> 10. Compare IOT vs Cloud Computing.

Completed with eb2cb6cbd0a1fd07f4c9c331ae6a32d943fe4bd0 commit
