### ISSUE TITLE
BCC Notes Tracker

### ISSUE THREAD

**Issue by dog-broad** [dog-broad/3_2-Needs#5]
# Unit 1

- [x] State and Explain the core components of Blockchain.
- [x] Explain the importance of Merkle Trees in Blockchain.
- [x] Explain Alternative Coins in detail.
- [x] Explain in detail about Block header.
- [x] Explain the concept of GAS.
- [x] State the process of creating a Block.

# Unit 2

- [x] Explain in detail about the Mining systems
- [x] Write about bitcoin scripts.
- [x] Classify the Bitcoin wallets.
- [x] Explain the concept of anonymity in detail.
- [x] Explain in detail how forks work and their classifications.
- [x] Explain the concept of Bitcoin transaction verification.
- [x] Explain the task of miners in Bitcoin Network.
- [x] Write about distributed consensus mechanism in detail.

# Unit 3

- [x] State the differences between PoW and PoS.
- [x] Write in detail about Sybil attacks.
- [x] Explain 51% attacks on Bitcoin network.
- [x] Explain Proof of Work consensus and the different attacks on PoW.
- [x] What is EVM? Explain characteristics of Ethereum Blockchain.
- [x] Discuss any three (Metamask, Myether, Coinbase) EVM Wallets.
- [x] Describe Smart contracts and explain Value types in Solidity
- [x] Discuss Key concepts in the Solidity Programming (arrays, functions, structs and solidity mapping) with examples.

# Unit 4

- [x] Explain the architecture of Hyperledger Fabric with neat diagram.
- [x] Discuss the below Libraries and tools of Hyperledger Fabric : (a) Indy  (b) Aries   (c) Caliper
- [x] Discuss the below Libraries and tools of Hyperledger Fabric: (a) Quilt   (b) Ursa    (c) Caliper
- [x] Explain Hyperledger fabric details
- [x] Describe Hyperledger Fabric MSP
- [x] Discuss Identity Management in Hyperledger Fabric
- [x] Explain Transaction Flow in Hyperledger Fabric step-by-step with neat diagram
- [x] Explain Hyperledger Fabric network setup step-by-step with neat diagram

# Unit 5

- [x] Discuss Non-Fungible Tokens
- [x] Describe Decentralized autonomous Organization(DAOs)
- [x] Discuss Solobound Tokens (SBT) with example  Solidity Program.
- [x] What are Zero-Knowledge Proofs? 
- [x] Discuss Usecase: Blockchain based E-Voting with Solidity Program.
- [x] Write short notes on a) Para Chains,b) Sunstrate Blockchian c)  Dune Analytics.Explain Layer-2 Protocols(Optimism and ZK-rollups).
- [x] Explain Usecase: Certificate Management with Solidity program.
- [x] Explain Usecase: Market place and Supply chain with example.
