### ISSUE TITLE
FSWD Notes Tracker

### ISSUE THREAD

**Issue by dog-broad** [dog-broad/3_2-Needs#6]
# Unit 1

- [x] Explain about SVG and Canvas with an example
- [x] What are the differences between HTML and HTML5?
- [x] Discuss about Geo Location API
- [x] Demonstrate Bootstrap - Setup with an example
- [x] Discuss CSS Navbar in detail
- [x] Explain about CSS position properties
- [x] Explain about web storage in detail
- [x] Construct the code for Video & Audio

# Unit 2

- [x] Discuss about javascript variables and its scope
- [x] Explain JQuery Selectors in detail
- [x] Explain about AJAX
- [x] Explain about form events in JQuery with an example
- [x] Explain about type of Arrays in javascript
- [x] Elaborate DOM Manipulation
- [x] Construct javascript code for Form validating at client side
- [x] Discuss about effects and animations in JQuery

# Unit 3

- [x] Discuss the process to create a Simple Server
- [x] Discuss detailed Installation of Node.js and npm
- [x] Demonstrate Express Setup in node.js
- [x] Discuss about Template Engines in Node.js
- [x] Compare SQL Databases and MongoDB at High level.
- [x] Explain about Middleware of Node MongoDB Driver
- [x] Create a UI form with user Registration, Password Encryption and Login functions using node Mongodb driver?
- [x] Explain about built in module of NodeJS with example

# Unit 4

- [x] Illustrate ngModel  with an example.
- [x] Distinguish AngularJS and Angular.
- [x] Demonstrate Data binding in Angular? And Explain Types of Binding.
- [x] What is Angular Framework, Construct Angular Application and write its steps to setup?
- [x] Describe the procedure to create Components in Angular
- [x] Explain http Module & Observable in Angular?
- [x] Construct the steps to fetch data from a service and display it in the component.
- [x] What are Angular JS Mouse Events and Explain in detail

# Unit 5

- [x] How will you create and configure a git repository?
- [x] Build the steps to create a new git local Repository and remote repository.
- [x] What is Git and why is it used?
- [x] Distinguish between Git and GitHub.
- [x] Examine git add, status, log, commit and push, branch, merge commands?
- [x] How to deploy your website on heroku using github or git?
- [x] Identify the features and benefits of using Git? 
- [x] What do you understand by the term ‘Version Control System’? Name a few Git commands with their function.
- [x] Write all test cases to test the project in Git
